name: potenday
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # google
  google_maps_flutter:
  google_maps_flutter_android:
  google_maps_flutter_platform_interface:

  # google firebase

  # sensor

  # etc
  url_launcher:
  provider:
  permission_handler:
  device_info_plus:
  sqflite: ^2.2.8+4
  http: ^1.1.2
  http_parser: ^4.0.0
  transition: ^2.0.2
  table_calendar: ^3.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  #android: "launcher_icon"
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/symbol.png"
  #image_path_android: "assets/icon/an_symbol.png"
  #min_sdk_android: 21 # android min sdk min:16, default 21
  #adaptive_icon_background: "#ff663399"
  #adaptive_icon_foreground: "assets/icon/an_symbol.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.ttf
        - asset: assets/fonts/NotoSansKR-Bold.ttf
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
        - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
        - asset: assets/fonts/NotoSansKR-Light.ttf
        - asset: assets/fonts/NotoSansKR-Medium.ttf
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
        - asset: assets/fonts/NotoSansKR-Thin.ttf

