name: potenday
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # google
  google_maps_flutter:
  google_maps_flutter_android:
  google_maps_flutter_platform_interface:

  # google firebase

  # sensor

  # etc
  url_launcher:
  provider:
  permission_handler:
  device_info_plus:
  sqflite: ^2.2.8+4
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  #android: "launcher_icon"
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/symbol.png"
  #image_path_android: "assets/icon/an_symbol.png"
  #min_sdk_android: 21 # android min sdk min:16, default 21
  #adaptive_icon_background: "#ff663399"
  #adaptive_icon_foreground: "assets/icon/an_symbol.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/

#  fonts:
#    - family: NanumSquareRound
#      fonts:
#        - asset: assets/fonts/NanumSquareRoundB.ttf
#        - asset: assets/fonts/NanumSquareRoundEB.ttf
#        - asset: assets/fonts/NanumSquareRoundL.ttf
#        - asset: assets/fonts/NanumSquareRoundR.ttf
#        - asset: assets/fonts/NanumSquareRoundOTFB.otf
#        - asset: assets/fonts/NanumSquareRoundOTFEB.otf
#        - asset: assets/fonts/NanumSquareRoundOTFL.otf
#        - asset: assets/fonts/NanumSquareRoundOTFR.otf
