spring:
  security:
    oauth2:
      client:
        registration:

          google:
            client-id: 45515521416-ac0vc7t10217rtlol7hfq2d50fvrggh3.apps.googleusercontent.com
            client-secret: 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
            #            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            #            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile,email

          naver:
            client-id: SEgvaQwMG2MMazk2cKqB
            client-secret: w3pf5BvEAO
            #            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            #            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
            authorization_grant_type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver


          kakao:
            client-id: 3fef35d3833aa22e91d923006d8d4fa3
            client-secret: dn8LdztjvTb8zBXeU0d5xHgHrm9ZE6C5
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email, name
            client-name: Kakao

        provider:

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id