cloud:
  aws:
    s3:
      bucket: pupcket-bucket
      credentials:
        access-key: 6CfOKBAU6yf0l7vk7doL
        secret-key: PMEb19qj1PkUfPvAwRDHF3JlECQjD3SlkJiufL8D
      stack:
        auto: false
      region:
        static: ap-northeast-2
      endpoint: https://kr.object.ncloudstorage.com


spring:
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /users/이선로/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)