name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # 프로젝트의 server 디렉토리로 이동
    - name: Change directory to server
      working-directory: ./Pupket/server
      run: pwd  # 현재 디렉토리 확인 (디버깅용)

    # Gradle Wrapper에 실행 권한 추가
    - name: Set up Gradle wrapper
      run: chmod +x ./gradlew

    # Spring Boot 어플리케이션 Build (1)
    - name: Spring Boot Build
      run: ./gradlew clean build -x test

    # Docker 이미지 Build (2)
    - name: Docker image build
      working-directory: ./Pupket/server  # Dockerfile 위치를 명시
      run: docker build -t leesunro/pupcket:temp .

    # DockerHub Login (3)
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Docker Hub push (4)
    - name: Docker Hub push
      run: docker push leesunro/pupcket:temp
