name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # JDK 17 설정 추가
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Gradle Wrapper에 실행 권한 추가
    - name: Set up Gradle wrapper
      run: chmod +x ./server/gradlew

    # Spring Boot 어플리케이션 Build (1)
    - name: Spring Boot Build
      run: cd ./server && ./gradlew clean build -x test
    
    # Copy secret
    - name: Copy secret
      env:
        OCCUPY_SECRET: ${{ secrets.OCCUPY_SECRET }}
        OCCUPY_SECRET_DIR: server/src/main/resources
        OCCUPY_SECRET_DIR_FILE_NAME: application-secret.yml
      run: echo $OCCUPY_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME
    
    # Docker 이미지 Build (2)
    - name: Docker image build
      run: cd ./server && docker build -t leesunro/pupcket:temp .
    
    # DockerHub Login (3)
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Docker Hub push (4)
    - name: Docker Hub push
      run: docker push leesunro/pupcket:temp
